In [ ]:
import torch
import numpy as np

In [ ]:
data = [[1, 2], [3, 4]]
torch.tensor(data) #Creating tensor

tensor([[1, 2],
        [3, 4]])

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array) #Creating tensor from numpy array
x_np

tensor([[1, 2],
        [3, 4]])

In [ ]:
x_ones = torch.ones_like(x_np) # Creating similar tensors
x_ones

tensor([[1, 1],
        [1, 1]])

In [ ]:
x_rand = torch.rand_like(x_np, dtype=torch.float) # Overrides datatype of x_data, [0,1]
x_rand

tensor([[0.8202, 0.3266],
        [0.1097, 0.2273]])

In [ ]:
shape = (2, 3,) # a tuple of dimensions
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.2641, 0.4552, 0.9951],
        [0.6306, 0.5674, 0.2450]])

In [ ]:
tns = torch.rand(3, 4)
tns.shape

torch.Size([3, 4])

In [ ]:
tns.dtype

torch.float32

In [ ]:
tns.device

device(type='cpu')

In [ ]:
tns.to("mps")

tensor([[0.7319, 0.3989, 0.5575, 0.1720],
        [0.1919, 0.8481, 0.9034, 0.3079],
        [0.7538, 0.9811, 0.0521, 0.5025]], device='mps:0')

In [ ]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"

In [ ]:
tns.to(device)
tns.device

device(type='cpu')

In [ ]:
tns2 = torch.rand(4,4)
tns2

tensor([[0.9274, 0.3883, 0.7099, 0.5540],
        [0.4095, 0.2667, 0.9046, 0.7817],
        [0.9408, 0.5752, 0.3026, 0.2697],
        [0.1482, 0.5563, 0.7183, 0.1569]])

In [ ]:
tns2[:, 0] # First column

tensor([0.9274, 0.4095, 0.9408, 0.1482])

In [ ]:
tns2[0] # First row 

tensor([0.9274, 0.3883, 0.7099, 0.5540])

In [ ]:
tns2[..., -1] # Last column
'''
... means “expand to however many : slices are needed to cover all the remaining dimensions.”
x = torch.arange(2*3*4).reshape(2, 3, 4)
x[..., -1] → shape [2, 3]
It selects the last element in the last dimension (size 4 → index -1).
Equivalent to x[:, :, -1].
'''

'\n... means “expand to however many : slices are needed to cover all the remaining dimensions.”\nx = torch.arange(2*3*4).reshape(2, 3, 4)\nx[..., -1] → shape [2, 3]\nIt selects the last element in the last dimension (size 4 → index -1).\nEquivalent to x[:, :, -1].\n'

In [ ]:
x = torch.arange(2*3*4).reshape(2, 3, 4)
x[:,:,-1].shape

torch.Size([2, 3])

In [ ]:
x[:, -1]

tensor([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])

In [ ]:
x[..., -1]

tensor([[ 3,  7, 11],
        [15, 19, 23]])

In [ ]:
tns3 = torch.cat([tns, tns], dim=1) # Join horizontally
tns3.shape

torch.Size([3, 8])

In [ ]:
tns4 = torch.cat([tns, tns, tns], dim=0) # Join vertically
tns4.shape

torch.Size([9, 4])

In [ ]:
y = tns @ tns.T
y

tensor([[1.0353, 1.0355, 1.0586],
        [1.0355, 1.6672, 1.1785],
        [1.0586, 1.1785, 1.7859]])

In [ ]:
y2 = tns.matmul(tns.T)
y2

tensor([[1.0353, 1.0355, 1.0586],
        [1.0355, 1.6672, 1.1785],
        [1.0586, 1.1785, 1.7859]])

In [ ]:
tns.sum()

tensor(6.4012)

In [ ]:
tns

tensor([[0.7319, 0.3989, 0.5575, 0.1720],
        [0.1919, 0.8481, 0.9034, 0.3079],
        [0.7538, 0.9811, 0.0521, 0.5025]])

In [ ]:
tns.add_(5)

tensor([[5.7319, 5.3989, 5.5575, 5.1720],
        [5.1919, 5.8481, 5.9034, 5.3079],
        [5.7538, 5.9811, 5.0521, 5.5025]])

In [ ]:
tns

tensor([[5.7319, 5.3989, 5.5575, 5.1720],
        [5.1919, 5.8481, 5.9034, 5.3079],
        [5.7538, 5.9811, 5.0521, 5.5025]])

In [ ]:
tns + 5

tensor([[10.7319, 10.3989, 10.5575, 10.1720],
        [10.1919, 10.8481, 10.9034, 10.3079],
        [10.7538, 10.9811, 10.0521, 10.5025]])

In [ ]:
tns

tensor([[5.7319, 5.3989, 5.5575, 5.1720],
        [5.1919, 5.8481, 5.9034, 5.3079],
        [5.7538, 5.9811, 5.0521, 5.5025]])

In [ ]:
t = torch.ones(5)
n = t.numpy()
t, n

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
t.add_(5)

tensor([6., 6., 6., 6., 6.])

In [ ]:
n

array([6., 6., 6., 6., 6.], dtype=float32)