In [ ]:
import torch
import numpy as np

In [ ]:
data = [[1, 2], [3, 4]]
torch.tensor(data) #Creating tensor

tensor([[1, 2],
        [3, 4]])

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array) #Creating tensor from numpy array
x_np

tensor([[1, 2],
        [3, 4]])

In [ ]:
x_ones = torch.ones_like(x_np) # Creating similar tensors
x_ones

tensor([[1, 1],
        [1, 1]])

In [ ]:
x_rand = torch.rand_like(x_np, dtype=torch.float) # Overrides datatype of x_data, [0,1]
x_rand

tensor([[0.5084, 0.8146],
        [0.6544, 0.8614]])

In [ ]:
shape = (2, 3,) # a tuple of dimensions
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.4290, 0.8476, 0.7695],
        [0.5253, 0.7012, 0.1514]])

In [ ]:
tns = torch.rand(3, 4)
tns.shape

torch.Size([3, 4])

In [ ]:
tns.dtype

torch.float32

In [ ]:
tns.device

device(type='cpu')

In [ ]:
tns.to("mps")

tensor([[0.8596, 0.3055, 0.3644, 0.1697],
        [0.4827, 0.6311, 0.7365, 0.7154],
        [0.0461, 0.7705, 0.3015, 0.6800]], device='mps:0')

In [ ]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"

In [ ]:
tns.to(device)
tns = tns.to(device)
tns.device

device(type='mps', index=0)

In [ ]:
tns2 = torch.rand(4,4)
tns2

tensor([[0.3030, 0.9305, 0.3124, 0.0954],
        [0.0659, 0.4072, 0.7490, 0.8800],
        [0.8662, 0.5132, 0.1904, 0.8714],
        [0.2349, 0.8887, 0.7812, 0.0694]])

In [ ]:
tns2[:, 0] # First column

tensor([0.3030, 0.0659, 0.8662, 0.2349])

In [ ]:
tns2[0] # First row 

tensor([0.3030, 0.9305, 0.3124, 0.0954])

In [ ]:
tns2[..., -1] # Last column
'''
... means “expand to however many : slices are needed to cover all the remaining dimensions.”
x = torch.arange(2*3*4).reshape(2, 3, 4)
x[..., -1] → shape [2, 3]
It selects the last element in the last dimension (size 4 → index -1).
Equivalent to x[:, :, -1].
'''

'\n... means “expand to however many : slices are needed to cover all the remaining dimensions.”\nx = torch.arange(2*3*4).reshape(2, 3, 4)\nx[..., -1] → shape [2, 3]\nIt selects the last element in the last dimension (size 4 → index -1).\nEquivalent to x[:, :, -1].\n'

In [ ]:
x = torch.arange(2*3*4).reshape(2, 3, 4)
x[:,:,-1].shape

torch.Size([2, 3])

In [ ]:
x[:, -1]

tensor([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])

In [ ]:
x[..., -1]

tensor([[ 3,  7, 11],
        [15, 19, 23]])

In [ ]:
tns3 = torch.cat([tns, tns], dim=1) # Join horizontally
tns3.shape

torch.Size([3, 8])

In [ ]:
tns4 = torch.cat([tns, tns, tns], dim=0) # Join vertically
tns4.shape

torch.Size([9, 4])

In [ ]:
y = tns @ tns.T
y

tensor([[0.9938, 0.9976, 0.5003],
        [0.9976, 1.6856, 1.2171],
        [0.5003, 1.2171, 1.1491]], device='mps:0')

In [ ]:
y2 = tns.matmul(tns.T)
y2

tensor([[0.9938, 0.9976, 0.5003],
        [0.9976, 1.6856, 1.2171],
        [0.5003, 1.2171, 1.1491]], device='mps:0')

In [ ]:
tns.sum()

tensor(6.0631, device='mps:0')

In [ ]:
tns

tensor([[0.8596, 0.3055, 0.3644, 0.1697],
        [0.4827, 0.6311, 0.7365, 0.7154],
        [0.0461, 0.7705, 0.3015, 0.6800]], device='mps:0')

In [ ]:
tns.add_(5)

tensor([[5.8596, 5.3055, 5.3644, 5.1697],
        [5.4827, 5.6311, 5.7365, 5.7154],
        [5.0461, 5.7705, 5.3015, 5.6800]], device='mps:0')

In [ ]:
tns

tensor([[5.8596, 5.3055, 5.3644, 5.1697],
        [5.4827, 5.6311, 5.7365, 5.7154],
        [5.0461, 5.7705, 5.3015, 5.6800]], device='mps:0')

In [ ]:
tns + 5

tensor([[10.8596, 10.3055, 10.3644, 10.1697],
        [10.4827, 10.6311, 10.7365, 10.7154],
        [10.0461, 10.7705, 10.3015, 10.6800]], device='mps:0')

In [ ]:
tns

tensor([[5.8596, 5.3055, 5.3644, 5.1697],
        [5.4827, 5.6311, 5.7365, 5.7154],
        [5.0461, 5.7705, 5.3015, 5.6800]], device='mps:0')

In [ ]:
t = torch.ones(5)
n = t.numpy()
t, n

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
t.add_(5)

tensor([6., 6., 6., 6., 6.])